Repository f3d-app/f3d, pull requests merged in 2025-09, with the labels that each got.

#2454 CI: Move from checkboxes to labels for CI triggering
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-docker-images.yml
  .github/workflows/ci.yml
  .github/workflows/labelize.yml
  .github/workflows/style-checks.yml
  CONTRIBUTING.md
Labels: ci:full

#2458 CI: Add a missing skip
  .github/workflows/ci.yml
Labels: ci:fast, ci:full

#2455 Rework Style Check
  .github/workflows/style-checks.yml
Labels: ci:fast

#2452 Refactor WebAssembly package
  .gitattributes
  .github/ISSUE_TEMPLATE/new_release.md
  .github/actions/wasm-ci/action.yml
  .github/workflows/ci.yml
  .gitignore
  doc/dev/BUILD.md
  doc/dev/BUILD_WASM.md
  doc/libf3d/LANGUAGE_BINDINGS.md
  examples/libf3d/web/index.html
  examples/libf3d/web/package.json
  examples/libf3d/web/public/f3d.vtp
  examples/libf3d/web/public/favicon.ico
  examples/libf3d/web/public/icon256.png
  examples/libf3d/web/public/manifest.json
  examples/libf3d/web/src/main.js
  examples/libf3d/web/vite.config.js
  package.json
  testing/baselines/TestWasmOptions.png
  webassembly/CMakeLists.txt
  webassembly/F3DEmscriptenBindings.cxx
  webassembly/README.md
  webassembly/app.html
  webassembly/build.sh
  webassembly/manifest.json
  webassembly/package.json
  webassembly/testing/CMakeLists.txt
  webassembly/testing/test.html.in
  webassembly/testing/test_options.js
  webassembly/testing/utils.js
Labels: ci:full

#2460 Fix web app base url
  .github/workflows/ci.yml
  examples/libf3d/web/vite.config.js
Labels: ci:full

#2466 Remove dupplicate gzip check in SPZ reader
  application/testing/CMakeLists.txt
  plugins/native/module/vtkF3DSPZReader.cxx
Labels: ci:fast, ci:full

#2469 Set HEX Color from command without required to escape it
  doc/user/COMMANDS.md
  library/private/interactor_impl.h
  library/public/interactor.h
  library/public/utils.h
  library/src/interactor_impl.cxx
  library/src/utils.cxx
  library/testing/TestSDKUtils.cxx
  python/F3DPythonBindings.cxx
  python/testing/test_interactor.py
  python/testing/test_utils.py
Labels: ci:fast, ci:full

#2479 Update VTK version and adapt to importer changes in VTK
  .github/workflows/versions.json
  library/testing/TestSDKEngineExceptions.cxx
  plugins/assimp/module/Testing/TestF3DAssimpImporter.cxx
  plugins/assimp/module/vtkF3DAssimpImporter.cxx
  plugins/assimp/module/vtkF3DAssimpImporter.h
  plugins/native/module/vtkF3DQuakeMDLImporter.cxx
  plugins/native/module/vtkF3DQuakeMDLImporter.h
  plugins/usd/module/Testing/TestF3DUSDImporter.cxx
  plugins/usd/module/vtkF3DUSDImporter.cxx
  plugins/usd/module/vtkF3DUSDImporter.h
Labels: ci:main, ci:full

#2484 Tests: Fix/Exclude recent flaky tests
  .github/actions/generic-ci/action.yml
  application/testing/CMakeLists.txt
  library/testing/CMakeLists.txt
Labels: ci:full
